# Generated by Django 6.0.5 on 2026-09-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('category', models.CharField(choices=[('hotel', 'هتل'), ('villa', 'ویلا'), ('apartment', 'آپارتمان'), ('ecolodge', 'بومگردی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('location', models.CharField(max_length=200, verbose_name='موقعیت')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت هر شب')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اقامتگاه',
                'verbose_name_plural': 'اقامتگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تصویر اقامتگاه',
                'verbose_name_plural': 'تصاویر اقامتگاه\u200cها',
                'ordering': ['created_at'],
            },
        ),
    ]
