# Generated by Django 6.0.5 on 2026-09-01 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('destination', models.CharField(max_length=200, verbose_name='مقصد')),
                ('duration', models.CharField(choices=[('1day', 'یک روزه'), ('2day', 'دو روزه'), ('3day', 'سه روزه'), ('week', 'یک هفته')], max_length=20, verbose_name='مدت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('itinerary', models.TextField(blank=True, verbose_name='برنامه سفر')),
                ('included_services', models.TextField(blank=True, verbose_name='خدمات شامل شده')),
                ('excluded_services', models.TextField(blank=True, verbose_name='خدمات شامل نشده')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserved_by', models.ManyToManyField(blank=True, related_name='reserved_tours', to=settings.AUTH_USER_MODEL, verbose_name='رزرو شده توسط')),
            ],
            options={
                'verbose_name': 'تور',
                'verbose_name_plural': 'تورها',
                'ordering': ['start_date'],
            },
        ),
    ]
